name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${author}

main: ${bukkit.mainclass}
softdepend: [${bukkit.depends}]
load: startup

commands:
   ElementalArrows:
      description: Basic command of ${project.name}
      usage: /ElementalArrows Help