name: ${project.name}
main: ${MainClass}
version: ${project.version}
description: ${project.description}
author: ${Author}
load: startup
softdepend: [${Depends}]
commands:
   ElementalArrows:
      description: Basic command of ${project.name}
      usage: /ElementalArrows Help